enum accountTypes {
  LOGIN_REQUEST = "LOGIN_REQUEST",
  LOGIN_SUCCESS = "LOGIN_SUCCESS",
  LOGIN_FAILURE = "LOGIN_FAILURE",

  REGISTER_REQUEST = "USER_REGISTER_REQUEST",
  REGISTER_SUCCESS = "USER_REGISTER_SUCCESS",
  REGISTER_FAILURE = "USER_REGISTER_FAILURE",

  LOGOUT_REQUEST = "LOGOUT_REQUEST",
  LOGOUT_SUCCESS = "LOGOUT_SUCCESS",

  SIGN_UP_REQUEST = "SIGN_UP_REQUEST",
  SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE = "SIGN_UP_FAILURE",

  GET_CURRENT_USER_REQUEST = "GET_CURRENT_USER_REQUEST",
  GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS",
  GET_CURRENT_USER_FAILURE = "GET_CURRENT_USER_FAILURE",
}

export default accountTypes;
