enum cartTypes {
  ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST",
  ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS",
  ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE",

  REMOVE_FROM_CART_REQUEST = "REMOVE_FROM_CART_REQUEST",
  REMOVE_FROM_CART_SUCCESS = "REMOVE_FROM_CART_SUCCESS",
  REMOVE_FROM_CART_FAILURE = "REMOVE_FROM_CART_FAILURE",

  REMOVE_FROM_SAVE_FOR_LATER_REQUEST = "REMOVE_FROM_SAVE_FOR_LATER_REQUEST",
  REMOVE_FROM_SAVE_FOR_LATER_SUCCESS = "REMOVE_FROM_SAVE_FOR_LATER_SUCCESS",
  REMOVE_FROM_SAVE_FOR_LATER_FAILURE = "REMOVE_FROM_SAVE_FOR_LATER_FAILURE",

  SAVE_FOR_LATER_REQUEST = "SAVE_FOR_LATER_REQUEST",
  SAVE_FOR_LATER_SUCCESS = "SAVE_FOR_LATER_SUCCESS",
  SAVE_FOR_LATER_FAILURE = "SAVE_FOR_LATER_FAILURE",

  MOVE_TO_CART_REQUEST = "MOVE_TO_CART_REQUEST",
  MOVE_TO_CART_SUCCESS = "MOVE_TO_CART_SUCCESS",
  MOVE_TO_CART_FAILURE = "MOVE_TO_CART_FAILURE",

  ADD_TO_WISHLIST_REQUEST = "ADD_TO_WISHLIST_REQUEST",
  ADD_TO_WISHLIST_SUCCESS = "ADD_TO_WISHLIST_SUCCESS",
  ADD_TO_WISHLIST_FAILURE = "ADD_TO_WISHLIST_FAILURE",
}

export default cartTypes;
