enum courseTypes {
  COURSE_REQUEST = "COURSE_REQUEST",
  COURSE_SUCCESS = "COURSE_SUCCESS",
  COURSE_FAILURE = "COURSE_FAILURE",

  CREATE_COURSE_REQUEST = "CREATE_COURSE_REQUEST",
  CREATE_COURSE_SUCCESS = "CREATE_COURSE_SUCCESS",
}

export default courseTypes;
