enum curriculumTypes {
  CANCEL_EDIT_TITLE = "CANCEL_EDIT_TITLE",
  SET_ELEMENT_DISPLAY = "SET_ELEMENT_DISPLAY",
  DISPLAY_OPTION = "DISPLAY_OPTION",
  DISPLAY_CREATE_LECTURE = "DISPLAY_CREATE_LECTURE",
  DISPLAY_CREATE_SECTION = "DISPLAY_CREATE_SECTION",
}

export default curriculumTypes;
