enum learningTypes {
  GET_COURSE_IN_LEARNING_REQUEST = "GET_COURSE_IN_LEARNING_REQUEST",
  GET_COURSE_IN_LEARNING_SUCCESS = "GET_COURSE_IN_LEARNING_SUCCESS",

  GET_SECTIONS_IN_LEARNING_REQUEST = "GET_SECTIONS_IN_LEARNING_REQUEST",
  GET_SECTIONS_IN_LEARNING_SUCCESS = "GET_SECTIONS_IN_LEARNING_SUCCESS",

  UPDATE_PROGRESS_REQUEST = "UPDATE_PROGRESS_REQUEST",
  UPDATE_PROGRESS_SUCCESS = "UPDATE_PROGRESS_SUCCESS",

  GET_PROGRESS_REQUEST = "GET_PROGRESS_REQUEST",
  GET_PROGRESS_SUCCESS = "GET_PROGRESS_SUCCESS",

  RESET_STATE_LEARNING = "RESET_STATE_LEARNING",
}

export default learningTypes;
